### ISSUE TITLE
ios safari 没法在 body上设置 overflow：hidden，导致页面还能够滚动

### ISSUE THREAD

**Issue by aizigao** [react-component/dialog#66]
在ios body上用js设置overflow：hidden 是失效，所以是否应该开放出载入点。。

https://github.com/react-component/dialog/blob/master/src/DialogWrap.tsx#L29

**Comment by aizigao** [comment]
原来是有的woc

**Comment by aizigao** [comment]
虽然有 getContainer 方法， 设置了 container，关闭时整个节点都移除了，导致那个container只能用一次

**Comment by aizigao** [comment]
加入下面的代码可以解决 hidden失效问题

```css
html, body {
  /* 解决弹窗 ios上 overhidden 失效的问题 */
  width: 100%;
  height: 100%;
  overflow: scroll;
  -webkit-overflow-scrolling: touch;
}
```
